<?php

namespace Database\Seeders;

use App\Models\Karyawan;
use App\Models\Unitperusahaan;
use Illuminate\Database\Seeder;

class KaryawanSeeder extends Seeder
{
    public function run(): void
    {
        $unitIds = Unitperusahaan::pluck('id', 'unit')->toArray();

        $karyawans = [
            ['nik' => '7120124002', 'nama_lengkap' => 'IRA CARLINA', 'jabatan' => 'Direktur', 'posisi' => 'DIREKTUR', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Wayang', 'no_hp' => '085716009449', 'foto' => null, 'password' => '$2y$12$6RWM8oG2wRYJEuQElrM2H.xH43qj4gLBJpeROQawn5Ee5mp3w7KoC'],
            ['nik' => '7120124003', 'nama_lengkap' => 'RIZKY PUTRA NINDA', 'jabatan' => 'Manager', 'posisi' => 'MANAGER CRM', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Cerapproval', 'no_hp' => '083874659062', 'foto' => null, 'password' => '$2y$12$eUT6./EggUqektoJTHZx3urNQGIkgi4Mc8AjowDlycAf4PfolTBle'],
            ['nik' => '7120124004', 'nama_lengkap' => 'M FAIRUZ ADVIALDINI', 'jabatan' => 'Manager', 'posisi' => 'MANAGER PMO', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Cerapproval', 'no_hp' => '085779690950', 'foto' => null, 'password' => '$2y$12$Ko.SX4k.qQB8ehH9uYuL/ecOaMX1G17Ex8vb3LEDa7bbAQoGrrLZq'],
            ['nik' => '7120124005', 'nama_lengkap' => 'KARISMA INSANI', 'jabatan' => 'SPV', 'posisi' => 'SPV PMO', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Cerapproval', 'no_hp' => '081296600296', 'foto' => null, 'password' => '$2y$12$N0Fj6KD.CL.ch3vNMch/d..QFC38BLNaaIhaFhOG8fgKfIY9qffSG'],
            ['nik' => '7120124006', 'nama_lengkap' => 'HANAN DEVI', 'jabatan' => 'Staff', 'posisi' => 'STAFF PMO', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Cerapproval', 'no_hp' => '08987839234', 'foto' => null, 'password' => '$2y$12$03.NKY2DD1TnWbuVMD3O.ezvuw9v56DwL8K.qgwfAyiH6KMfMx36m'],
            ['nik' => '7120124007', 'nama_lengkap' => 'RIDHO AL FADLY', 'jabatan' => 'Staff', 'posisi' => 'SENIOR STAFF PMO', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Wayang', 'no_hp' => '085881230951', 'foto' => null, 'password' => '$2y$12$PjA7aZCgE.dEE0qJh01udOsxx0tsnTdbNlGg3XdJAaAm1oTKoJ2y6'],
            ['nik' => '7120124008', 'nama_lengkap' => 'IZAZ ITZHAR', 'jabatan' => 'Staff', 'posisi' => 'ART DIRECTOR & CINEMOGRAPHER', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Lensagram', 'no_hp' => '087773903337', 'foto' => null, 'password' => '$2y$12$i73Idied0Y0jKxkCn6LYwelToH9Xz3QK8Wn/ZyKhxq./W.ZT5aJRy'],
            ['nik' => '7120124009', 'nama_lengkap' => 'MUNIKHA SALMA', 'jabatan' => 'Staff', 'posisi' => 'ADMIN STAFF', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Cerapproval', 'no_hp' => '08990021064', 'foto' => null, 'password' => '$2y$12$5xuDIN7qHAhZS0ANGdJbh.DUhzLk6fzH.rsFKKkQ1TfIeN4o.5yRa'],
            ['nik' => '7120124010', 'nama_lengkap' => 'MUHAMMAD RAIHAN', 'jabatan' => 'Staff', 'posisi' => 'SALES AGENT', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Arthama', 'no_hp' => '088289687756', 'foto' => null, 'password' => '$2y$12$8RUO6rjjX3lcTOkL0Rx/W.JJzJp9sjtffPflEd5YOgmZuAe.d6A2O'],
            ['nik' => '7120124011', 'nama_lengkap' => 'NAUFAIL IMAMUDDIN', 'jabatan' => 'Manager', 'posisi' => 'HRGA MANAGER', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Wayang', 'no_hp' => '089661228014', 'foto' => null, 'password' => '$2y$12$3aFedJG2nVbVNz09kdk20.WzKMRYI3/T.tDvkx3uPJtHg5.wjzN56'],
            ['nik' => '7120124018', 'nama_lengkap' => 'PANJI KESUMO', 'jabatan' => 'GM', 'posisi' => 'GM OPS & MARKETING', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Cerapproval', 'no_hp' => '08127311818', 'foto' => null, 'password' => '$2y$12$soHcS.eOz.1qC.EdrUCeb.gUNI7cBXIb9HIbaUO68ZwMB5iMKuq/S'],
            ['nik' => '7120124019', 'nama_lengkap' => 'RIZKYNIA NABILA', 'jabatan' => 'Staff', 'posisi' => 'DIGITAL MARKETING SPECIALIST', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Lensagram', 'no_hp' => '082228565188', 'foto' => null, 'password' => '$2y$12$5lGM0EAX/LasHbuDXH0JVOoE5skjIfulUcDLwxV/WoQONj3LFWuMS'],
            ['nik' => '7120124020', 'nama_lengkap' => 'RAKHA NATHA', 'jabatan' => 'Direktur', 'posisi' => 'HEAD OF BUSINESS DEVELOPMENT', 'role_approved' => 'Manager', 'atasan_nik' => null, 'unit' => 'Lensagram', 'no_hp' => '081995327248', 'foto' => null, 'password' => '$2y$12$ZzC7X/m1Z4e1Ph0Rs79H2uq1iEqjee5Qmp3YQ0QPIGJlKtNmWOUX.', 'remember_token' => null],
            ['nik' => '7120124021', 'nama_lengkap' => 'DEMA ILMI ANNISA AMALLIAH MALIK', 'jabatan' => 'Staff', 'posisi' => 'SENIOR STAFF FINANCE', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Cerapproval', 'no_hp' => '087748680756', 'foto' => null, 'password' => '$2y$12$n94/tSZ.fPqO4bw3OSL0gu8MssJqxlv0OFRMFZ6F2PLRRcVNBaOQa'],
            ['nik' => '7120124022', 'nama_lengkap' => 'UMI ROSIDAH', 'jabatan' => 'Staff', 'posisi' => 'ADVOKAT', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Werkudoro', 'no_hp' => '085865637514', 'foto' => null, 'password' => '$2y$12$qO5P1ThZN52t1uQ2uocTKeACxBq0s8ggyekUpIG8DjGaa0WnoQpNi'],
            ['nik' => '7120124023', 'nama_lengkap' => 'INTAN MEDINA UTAMI', 'jabatan' => 'Staff', 'posisi' => 'ADMIN SALES', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Cerapproval', 'no_hp' => '085892996695', 'foto' => null, 'password' => '$2y$12$L0fEinDspnyim4CxBkSmlOkW4e7c1em.Pz7/7JLzr/oZIuCJIE6k6'],
            ['nik' => '7120124024', 'nama_lengkap' => 'SYAHNAZ DESI ADELLIA', 'jabatan' => 'Staff', 'posisi' => 'KEPALA CABANG BTW JAKARTA', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'BTW Academy', 'no_hp' => '089606471524', 'foto' => null, 'password' => '$2y$12$crPvBaQPc9a.SPXROGeW.uTjeNYITXOunxgorWciD15Hgr520vOjW'],
            ['nik' => '7120124025', 'nama_lengkap' => "AL'ADDIN ZAINUL UMAM", 'jabatan' => 'Staff', 'posisi' => 'STAFF', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Wayang', 'no_hp' => '081575819505', 'foto' => null, 'password' => '$2y$12$u02uX5j7wiVP3bmswOZneupIlPSOpzfSQPONEg1Jh5cdKX4g0oGa.'],
            ['nik' => '7120124026', 'nama_lengkap' => 'ESA TRIA HAMKA', 'jabatan' => 'Staff', 'posisi' => 'STAFF', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Wayang', 'no_hp' => '088224627773', 'foto' => null, 'password' => '$2y$12$sTS8wMK78MjiXS26yNA3v.7it0jLRpC6fXtP/QVUQaVBnxsFKY8lC'],
            ['nik' => '7120124027', 'nama_lengkap' => 'DIDI DARMAWAN', 'jabatan' => 'Staff', 'posisi' => 'SALES MARKETING', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Arthama', 'no_hp' => '089513101140', 'foto' => null, 'password' => '$2y$12$JuH7ZiO74Wo2IiIuWvn.IeECso.Is8kPnzWrl/ixUXntMazHwfjMy'],
            ['nik' => '7120124028', 'nama_lengkap' => 'AZIRA SAUSAN DALIA', 'jabatan' => 'Staff', 'posisi' => 'ADMIN SKILLNATION', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'BTW Academy', 'no_hp' => '085921982401', 'foto' => null, 'password' => '$2y$12$mZpsMjOFijhY5v1C2V7cjOUyEV.HY3LDL.jc5UsCGY1lin6LqrBE.'],
            ['nik' => '7120124029', 'nama_lengkap' => 'ARSYI SYARQIYYA', 'jabatan' => 'Staff', 'posisi' => 'MARKETING ADMIN', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Lensagram', 'no_hp' => '085879368953', 'foto' => null, 'password' => '$2y$12$iDHQN8AkfxwOEj1seNFoGOjgGUpjQb8t4pvaq7pN9XkW2C9D6wu5e'],
            ['nik' => '7120124030', 'nama_lengkap' => 'NICEA ERYANAWATI', 'jabatan' => 'Staff', 'posisi' => 'GRAPHIC DESIGNER', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Lensagram', 'no_hp' => '085782680271', 'foto' => null, 'password' => '$2y$12$Tr6zicVXNAi7AaJglr6.zOqpcWBYsFyT40vaUnJcsp/gLWFmma3E.'],
            ['nik' => '7120124031', 'nama_lengkap' => 'MUHAMMAD UMAR', 'jabatan' => 'Staff', 'posisi' => 'STAFF RFE', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Cerapproval', 'no_hp' => '089653249127', 'foto' => null, 'password' => '$2y$12$644368chQ1Zj69Nip2CNSuFzw5QkvQk0KqQZtPueiEe1u2NvciDy6'],
            ['nik' => '7120124032', 'nama_lengkap' => 'LINGGAR ADITYA', 'jabatan' => 'Staff', 'posisi' => 'STAFF SNI', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Cerapproval', 'no_hp' => '082284558776', 'foto' => null, 'password' => '$2y$12$1/gt/nuLcBmO3o5vU06wc.k6YWJrDrXACk2ODylYAcV2Uoq14h186'],
            ['nik' => '7120124033', 'nama_lengkap' => 'VALERIAN GIBHOR', 'jabatan' => 'Staff', 'posisi' => 'VIDEOEDITOR BY AI', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Cerapproval', 'no_hp' => '-', 'foto' => null, 'password' => '$2y$12$EdLMF6U2qcqgQ3esDExShuLAL/GrnvB2qbf.w1hxKtofqvZbBCLum'],
            ['nik' => '7120124034', 'nama_lengkap' => 'AHMAD FATONI', 'jabatan' => 'SPV', 'posisi' => 'SPV PMO (SNI SPECIALIST)', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Cerapproval', 'no_hp' => '085692500838', 'foto' => null, 'password' => '$2y$12$EpWNKsiM4wtZg/ijuUwuqObw0oQpNSNF9ixglkasqHkXiVQWzat02'],
            ['nik' => '7120124035', 'nama_lengkap' => 'WINDU EVILIA SUSANTO', 'jabatan' => 'Staff', 'posisi' => 'SENIOR STAFF FAT', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Cerapproval', 'no_hp' => '088293355815', 'foto' => null, 'password' => '$2y$12$.kpPjWPwDEIDyN91A0FLf..RUTLWQSt.1DCkU51ryc/zj/yefx1F2'],
            ['nik' => '7120124036', 'nama_lengkap' => 'RAYHAN SIMBOLON', 'jabatan' => 'Staff', 'posisi' => 'DIGITAL MARKETING', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Lensagram', 'no_hp' => '081368148341', 'foto' => null, 'password' => '$2y$12$4jDdzzPJ.v.N9DGte8NcUu1yTvq89Pf/Ph1jVPr9LiG5AsCXMSvcO'],
            ['nik' => '7120124037', 'nama_lengkap' => 'ANDHIKA YULIANTO', 'jabatan' => 'Staff', 'posisi' => 'SECURITY', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Wayang', 'no_hp' => '081389683834', 'foto' => null, 'password' => '$2y$12$FC8mFh8knC4otb758mO4SugvRCjU0DosivqyzRdAXglXkdVJrd.36'],
            ['nik' => '7120124038', 'nama_lengkap' => 'ACHMAD RIZAL', 'jabatan' => 'Staff', 'posisi' => 'SECURITY', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Wayang', 'no_hp' => '089525804741', 'foto' => null, 'password' => '$2y$12$Ie3zafW2HI.NUK0aVjeckON5Iz4I5svM0w0EQrBHcODvfNtfPz9Qe'],
            ['nik' => '7120124039', 'nama_lengkap' => 'TEGUH MULYA', 'jabatan' => 'Staff', 'posisi' => 'SECURITY', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Wayang', 'no_hp' => '081383287576', 'foto' => null, 'password' => '$2y$12$BWh1kYEoQP1sUppyNeXoweoZcrrm1R06B4YCBtuhQ6zA/ZnZ/2Soa'],
            ['nik' => '7120124040', 'nama_lengkap' => 'RIA ULY', 'jabatan' => 'Staff', 'posisi' => 'MARKETING', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Wayang', 'no_hp' => '085813733386', 'foto' => null, 'password' => '$2y$12$VI.4kedUnBFCrbTmm.4q8OOOFWcQ4Jex1wn9hv0UZ3YOPOeuhh2Ri'],
            ['nik' => '7120124041', 'nama_lengkap' => 'AIM NASYAHONY', 'jabatan' => 'Staff', 'posisi' => 'OFFICE BOY', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Wayang', 'no_hp' => '0895393061924', 'foto' => null, 'password' => '$2y$12$ovV7jdNGglNPijuBJS6YTu6VlfPm7/fWEX4DK0jDNSonMjuNbAz.a'],
            ['nik' => '7120124042', 'nama_lengkap' => 'EGI DANA', 'jabatan' => 'Staff', 'posisi' => 'OFFICE BOY', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Wayang', 'no_hp' => '088295785423', 'foto' => null, 'password' => '$2y$12$zdAcrMOqLLMY8A8hvtDPBOCqSq63X/zBSXkFMeQlobE2BuXWkGTT6'],
            ['nik' => '7120124043', 'nama_lengkap' => 'SYAHDAD FATURROHMAN', 'jabatan' => 'Intern', 'posisi' => 'HRGA INTERN', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Wayang', 'no_hp' => '081220816427', 'foto' => null, 'password' => '$2y$12$aQVh.xBduPQFLWTnYJaZceVoxp5MUZqKhFKt8qfBEh7xjd6GbTpT2'],
            ['nik' => '7120124044', 'nama_lengkap' => 'DINDA AJENG KHARISMA PUTRI', 'jabatan' => 'Intern', 'posisi' => 'HRGA INTERN', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'In Wayang', 'no_hp' => '089514103951', 'foto' => null, 'password' => '$2y$12$K34YIIsMtXDlDm.XdkSpyOpCt6JBzoT5knmIURxbpYPBIGShI0CZG'],
            ['nik' => '7120124045', 'nama_lengkap' => 'VIRANI RAMADHANI', 'jabatan' => 'Intern', 'posisi' => 'INTERN SEO', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'BTW Academy', 'no_hp' => '-', 'foto' => null, 'password' => '$2y$12$9eOzsPikfK.gTJZBb76Ll.yKm1Go5AxugnBOpdYb0krsXPqRHRwJ.'],
            ['nik' => '7120124046', 'nama_lengkap' => 'RYAN ALTAMIRANO', 'jabatan' => 'Intern', 'posisi' => 'VIDEO EDITOR INTERN', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Lensagram', 'no_hp' => '082184420253', 'foto' => null, 'password' => '$2y$12$0JjjJZA5vfygsykK1FPWm.vGxKUBxgCq1LHBO1WdqE7JDUJCeuTPu'],
            ['nik' => '7120124048', 'nama_lengkap' => 'NADILLA NUR AULIA', 'jabatan' => 'Staff', 'posisi' => 'RESEPSIONIS DAN MARKETING', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Wayang', 'no_hp' => '085777206951', 'foto' => null, 'password' => '$2y$12$6AudEHJxqdKMx53/OK2D6OCotjpT/LE2bXR11Xkx5YqTEbrQsMIZK'],
            ['nik' => '7120124049', 'nama_lengkap' => 'IZZA MAULANA', 'jabatan' => 'Intern', 'posisi' => 'MEDIA DAN CONTENT INTERN', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'BTW Academy', 'no_hp' => '085707753310', 'foto' => null, 'password' => '$2y$12$2J9j8BHQY.LGZuwaX6Yyt.rlSCDG78qEpJKOilppBAjBVmwHSOFfK'],
            ['nik' => '7120124051', 'nama_lengkap' => 'MUNIFAH', 'jabatan' => 'Staff', 'posisi' => 'ADMIN MEDIA SOSIAL', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Arthama', 'no_hp' => '-', 'foto' => null, 'password' => '$2y$12$CG7I5z1YreIUyVD72r8LHur7afpIy87G3lQnfoC73YdNtTh1Jys6.'],
            ['nik' => '7120124053', 'nama_lengkap' => 'ADITYA PUTRA WIJAYANTO', 'jabatan' => 'Staff', 'posisi' => 'WEB DEVELOPER', 'role_approved' => 'Staff', 'atasan_nik' => '7120124020', 'unit' => 'Lensagram', 'no_hp' => '082213840105', 'foto' => null, 'password' => '$2y$12$EI/Q3MMYkFg4075ze6TAAeDtHBSPe6v9Vs6X0fEPoLWLg4vKs8VJ.'],
            ['nik' => '7120124054', 'nama_lengkap' => 'ANASYA NASYWA', 'jabatan' => 'Intern', 'posisi' => 'PRAKERIN', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Cerapproval', 'no_hp' => '-', 'foto' => null, 'password' => '$2y$12$fmRprX9RVVcgLVYxM3IcOeYBSH5.5HC8KHtRbAzApnkty/oauN03.'],
            ['nik' => '7120124055', 'nama_lengkap' => 'NADYA RAJWA PURWANTO', 'jabatan' => 'Intern', 'posisi' => 'PRAKERIN', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Cerapproval', 'no_hp' => '-', 'foto' => null, 'password' => '$2y$12$BNQNVKcSbXFu1E..k521z.fETKf/z5zcQcs46ahXAMzJ4JDYzK0CW'],
            ['nik' => '7120124056', 'nama_lengkap' => 'SONIA AZZAHRA', 'jabatan' => 'Intern', 'posisi' => 'PRAKERIN', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Wayang', 'no_hp' => '-', 'foto' => null, 'password' => '$2y$12$oK/ZmWP9w.ya11Qd6QL5We/H63BhEx0YbjockCoexqTJibKG44Cey'],
            ['nik' => '7120124057', 'nama_lengkap' => 'BUNGA', 'jabatan' => 'Intern', 'posisi' => 'PRAKERIN', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Lensagram', 'no_hp' => '-', 'foto' => null, 'password' => '$2y$12$kByCJhOoxZ8e9.wotETH8eZH4pAx8q6NbYPvXnHwY4jHCUUYShrJi'],
            ['nik' => '7120124058', 'nama_lengkap' => 'LUKY VIRYA', 'jabatan' => 'Staff', 'posisi' => 'WEB DEVELOPER', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Lensagram', 'no_hp' => '-', 'foto' => null, 'password' => '$2y$12$B8FwPO46ttShuzPJaiJzI.7JBW9YLK.OmF5baTA81qtBz2gXKOOmm'],
            ['nik' => '7120124059', 'nama_lengkap' => 'KHOIRUL ROZIKIN', 'jabatan' => 'Intern', 'posisi' => 'PRAKERIN', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Lensagram', 'no_hp' => '-', 'foto' => null, 'password' => '$2y$12$b8sDOcQSbowCOm26mO/s8.ymvXOSlm6Wpay6genCARS4V6Ia6yvtq'],
            ['nik' => '7120124060', 'nama_lengkap' => 'SALMA NUR ARIS', 'jabatan' => 'Intern', 'posisi' => 'PRAKERIN', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Lensagram', 'no_hp' => '-', 'foto' => null, 'password' => '$2y$12$iyHXu2pTmHwpfgHWWwdyAObQ1P9QLow/EFwG/HsKv/SoQtfkEmop6'],
            ['nik' => '7120124061', 'nama_lengkap' => 'JAUHARATUL MASHUNAH', 'jabatan' => 'Intern', 'posisi' => 'PRAKERIN', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Lensagram', 'no_hp' => '-', 'foto' => null, 'password' => '$2y$12$/Bq9hHZq7gNmjPTJ5Ae/IeicGdistrL79ryCIltXCBNcor3PGC8wq'],
            ['nik' => '7120124062', 'nama_lengkap' => 'RIZQI MAULANA SAID', 'jabatan' => 'Intern', 'posisi' => 'PRAKERIN', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Lensagram', 'no_hp' => '-', 'foto' => null, 'password' => '$2y$12$jcSC4qS6FWqzx4Sl2Nrjfu1dr7.X4aX0O5sP7E6RikUc4MSNIDh.W'],
            ['nik' => '7120124063', 'nama_lengkap' => 'MOCHAMAD AJI CHALID HIDAYATULLAH', 'jabatan' => 'Staff', 'posisi' => 'ARSITEK', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Arthama', 'no_hp' => '083129627715', 'foto' => null, 'password' => '$2y$12$22h8/uURqHQigHYfczGtC.nk4usb70rsrBZjLh5L5nB2nq73Aj9jq'],
            ['nik' => '7120124064', 'nama_lengkap' => 'ADMIRAL DHUMAID', 'jabatan' => 'Intern', 'posisi' => 'INTERN LEGAL', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Werkudoro', 'no_hp' => '081284844256', 'foto' => null, 'password' => '$2y$12$ig7xqIDOcOs2tIhWDL59pObv.bvUoRTKikCf5AKYLIFd3c4aAfDHi'],
            ['nik' => '7120124065', 'nama_lengkap' => 'FAKHMI RAHMADI', 'jabatan' => 'Staff', 'posisi' => 'DIGITAL MARKETING SPECIALIST', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Lensagram', 'no_hp' => '085943295436', 'foto' => null, 'password' => '$2y$12$QEMlDV8b0m2qIqDEcMMs7eT6tHNNX7S6t8BfS8Mv1EceEG67uNHuO'],
            ['nik' => '7120124068', 'nama_lengkap' => 'MAULIDINA ARTIKA TRIVANI', 'jabatan' => 'Intern', 'posisi' => 'INTERN FINANCE', 'role_approved' => null, 'atasan_nik' => null, 'unit' => 'Cerapproval', 'no_hp' => '081298742125', 'foto' => null, 'password' => '$2y$12$zdk3ZxDFoZ.5BdhD5.MXV.s8DjzZAKsisb17RNTYN7AyVMWQzrhDW'],
        ];

        foreach ($karyawans as $data) {
            $data['unit_id'] = $unitIds[$data['unit']] ?? null;

            Karyawan::updateOrCreate(
                ['nik' => $data['nik']],
                $data
            );
        }
    }
}
